FROM node:20-alpine as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build::ssr

FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --only=production
COPY --from=build /app/dist/101417557-lab-test2-comp3133 .
EXPOSE 4200
CMD ["node", "server.mjs"]
