FROM node:18-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --only=production
COPY --from=build /app/dist/101417557-lab-test2-comp3133/server ./
COPY --from=build /app/dist/101417557-lab-test2-comp3133/browser ./browser
EXPOSE 4200
CMD ["node", "server.mjs"]